site_name: Azure AI Search Handbook
site_description: Comprehensive learning resource for Azure AI Search from beginner to expert
site_author: Azure AI Search Handbook Contributors
site_url: https://sudharsank.github.io/azure-ai-search-handbook

# Repository
repo_name: azure-ai-search-handbook
repo_url: https://github.com/sudharsank/azure-ai-search-handbook
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

# Navigation
nav:
  - Home: index.md
  - Setup:
    - Getting Started: setup/README.md
    - Azure AI Search Setup: setup/azure-ai-search-setup.md
    - Quick Reference: setup/quick-reference.md
  - Beginner:
    - Module 1 - Introduction & Setup: beginner/module-01-introduction-setup/documentation.md
    - Module 2 - Basic Search: 
      - Overview: beginner/module-02-basic-search/documentation.md
      - Prerequisites: beginner/module-02-basic-search/prerequisites.md
      - Best Practices: beginner/module-02-basic-search/best-practices.md
      - Practice & Implementation: beginner/module-02-basic-search/practice-implementation.md
      - Troubleshooting:
        - Search Operations: beginner/module-02-basic-search/search-troubleshooting.md
        - Prerequisites Setup: beginner/module-02-basic-search/prerequisites-troubleshooting.md
      - Code Samples:
        - Overview: beginner/module-02-basic-search/code-samples/README.md
        - Interactive Notebooks: beginner/module-02-basic-search/code-samples/notebooks/README.md
        - Python Examples:
          - Overview: beginner/module-02-basic-search/code-samples/python/README.md
          - 01 - Simple Text Search: beginner/module-02-basic-search/code-samples/python/01_simple_text_search.py
          - 02 - Phrase Search: beginner/module-02-basic-search/code-samples/python/02_phrase_search.py
          - 03 - Boolean Search: beginner/module-02-basic-search/code-samples/python/03_boolean_search.py
          - 04 - Wildcard Search: beginner/module-02-basic-search/code-samples/python/04_wildcard_search.py
          - 05 - Field Search: beginner/module-02-basic-search/code-samples/python/05_field_search.py
          - 06 - Result Processing: beginner/module-02-basic-search/code-samples/python/06_result_processing.py
          - 07 - Error Handling: beginner/module-02-basic-search/code-samples/python/07_error_handling.py
          - 08 - Search Patterns: beginner/module-02-basic-search/code-samples/python/08_search_patterns.py
        - JavaScript Examples:
          - Overview: beginner/module-02-basic-search/code-samples/javascript/README.md
          - 01 - Simple Text Search: beginner/module-02-basic-search/code-samples/javascript/01_simple_text_search.js
          - 02 - Phrase Search: beginner/module-02-basic-search/code-samples/javascript/02_phrase_search.js
          - 03 - Boolean Search: beginner/module-02-basic-search/code-samples/javascript/03_boolean_search.js
          - 04 - Wildcard Search: beginner/module-02-basic-search/code-samples/javascript/04_wildcard_search.js
          - 05 - Field Search: beginner/module-02-basic-search/code-samples/javascript/05_field_search.js
          - 06 - Result Processing: beginner/module-02-basic-search/code-samples/javascript/06_result_processing.js
          - 07 - Error Handling: beginner/module-02-basic-search/code-samples/javascript/07_error_handling.js
          - 08 - Search Patterns: beginner/module-02-basic-search/code-samples/javascript/08_search_patterns.js
        - C# Examples:
          - Overview: beginner/module-02-basic-search/code-samples/csharp/README.md
          - 01 - Simple Text Search: beginner/module-02-basic-search/code-samples/csharp/01_SimpleTextSearch.cs
          - 02 - Phrase Search: beginner/module-02-basic-search/code-samples/csharp/02_PhraseSearch.cs
          - 03 - Boolean Search: beginner/module-02-basic-search/code-samples/csharp/03_BooleanSearch.cs
          - 04 - Wildcard Search: beginner/module-02-basic-search/code-samples/csharp/04_WildcardSearch.cs
          - 05 - Field Search: beginner/module-02-basic-search/code-samples/csharp/05_FieldSearch.cs
          - 06 - Result Processing: beginner/module-02-basic-search/code-samples/csharp/06_ResultProcessing.cs
          - 07 - Error Handling: beginner/module-02-basic-search/code-samples/csharp/07_ErrorHandling.cs
          - 08 - Search Patterns: beginner/module-02-basic-search/code-samples/csharp/08_SearchPatterns.cs
        - REST API Examples:
          - Overview: beginner/module-02-basic-search/code-samples/rest/README.md
          - 01 - Simple Text Search: beginner/module-02-basic-search/code-samples/rest/01_simple_text_search.http
          - 02 - Phrase Search: beginner/module-02-basic-search/code-samples/rest/02_phrase_search.http
          - 03 - Boolean Search: beginner/module-02-basic-search/code-samples/rest/03_boolean_search.http
          - 04 - Wildcard Search: beginner/module-02-basic-search/code-samples/rest/04_wildcard_search.http
          - 05 - Field Search: beginner/module-02-basic-search/code-samples/rest/05_field_search.http
          - 06 - Result Processing: beginner/module-02-basic-search/code-samples/rest/06_result_processing.http
          - 07 - Error Handling: beginner/module-02-basic-search/code-samples/rest/07_error_handling.http
          - 08 - Search Patterns: beginner/module-02-basic-search/code-samples/rest/08_search_patterns.http
      # - Exercises: beginner/module-02-basic-search/exercises/README.md
    - Module 3 - Index Management:
      - Overview: beginner/module-03-index-management/documentation.md
      - Prerequisites: beginner/module-03-index-management/prerequisites.md
      - Code Samples:
        - Overview: beginner/module-03-index-management/code-samples/README.md
        - Interactive Notebooks: beginner/module-03-index-management/code-samples/notebooks/README.md
        - Python Examples:
          - Overview: beginner/module-03-index-management/code-samples/python/README.md
          - 01 - Create Basic Index: beginner/module-03-index-management/code-samples/python/01_create_basic_index.py
          - 02 - Schema Design: beginner/module-03-index-management/code-samples/python/02_schema_design.py
          - 03 - Data Ingestion: beginner/module-03-index-management/code-samples/python/03_data_ingestion.py
          - 04 - Index Operations: beginner/module-03-index-management/code-samples/python/04_index_operations.py
          - 05 - Performance Optimization: beginner/module-03-index-management/code-samples/python/05_performance_optimization.py
          - 06 - Error Handling: beginner/module-03-index-management/code-samples/python/06_error_handling.py
        - JavaScript Examples:
          - Overview: beginner/module-03-index-management/code-samples/javascript/README.md
          - 01 - Create Basic Index: beginner/module-03-index-management/code-samples/javascript/01_create_basic_index.js
          - 02 - Schema Design: beginner/module-03-index-management/code-samples/javascript/02_schema_design.js
          - 03 - Data Ingestion: beginner/module-03-index-management/code-samples/javascript/03_data_ingestion.js
          - 04 - Index Operations: beginner/module-03-index-management/code-samples/javascript/04_index_operations.js
          - 05 - Performance Optimization: beginner/module-03-index-management/code-samples/javascript/05_performance_optimization.js
          - 06 - Error Handling: beginner/module-03-index-management/code-samples/javascript/06_error_handling.js
        - C# Examples:
          - Overview: beginner/module-03-index-management/code-samples/csharp/README.md
          - 01 - Create Basic Index: beginner/module-03-index-management/code-samples/csharp/01_CreateBasicIndex.cs
          - 02 - Schema Design: beginner/module-03-index-management/code-samples/csharp/02_SchemaDesign.cs
          - 03 - Data Ingestion: beginner/module-03-index-management/code-samples/csharp/03_DataIngestion.cs
          - 04 - Index Operations: beginner/module-03-index-management/code-samples/csharp/04_IndexOperations.cs
          - 05 - Performance Optimization: beginner/module-03-index-management/code-samples/csharp/05_PerformanceOptimization.cs
          - 06 - Error Handling: beginner/module-03-index-management/code-samples/csharp/06_ErrorHandling.cs
        - REST API Examples:
          - Overview: beginner/module-03-index-management/code-samples/rest/README.md
          - 01 - Create Basic Index: beginner/module-03-index-management/code-samples/rest/01_create_basic_index.http
          - 02 - Schema Design: beginner/module-03-index-management/code-samples/rest/02_schema_design.http
          - 03 - Data Ingestion: beginner/module-03-index-management/code-samples/rest/03_data_ingestion.http
          - 04 - Index Operations: beginner/module-03-index-management/code-samples/rest/04_index_operations.http
          - 05 - Performance Optimization: beginner/module-03-index-management/code-samples/rest/05_performance_optimization.http
          - 06 - Error Handling: beginner/module-03-index-management/code-samples/rest/06_error_handling.http
      # - Exercises: beginner/module-03-index-management/exercises/README.md
    - Module 4 - Simple Queries: beginner/module-04-simple-queries/documentation.md
  - Intermediate:
    - Module 5 - Advanced Querying: intermediate/module-05-advanced-querying/documentation.md
    - Module 6 - Analyzers & Scoring: intermediate/module-06-analyzers-scoring/documentation.md
    - Module 7 - Facets & Aggregations: intermediate/module-07-facets-aggregations/documentation.md
    - Module 8 - Security & Access: intermediate/module-08-security-access/documentation.md
  - Advanced:
    - Module 9 - AI Enrichment: advanced/module-09-ai-enrichment/documentation.md
    - Module 10 - Vector & Semantic Search: advanced/module-10-vector-semantic-search/documentation.md
    - Module 11 - Performance Optimization: advanced/module-11-performance-optimization/documentation.md
    - Module 12 - Production Deployment: advanced/module-12-production-deployment/documentation.md
  - Reference:
    - API Reference: reference/api-reference.md
    - Quick Reference: reference/quick-reference.md
    - Troubleshooting: reference/troubleshooting.md

# Extra
# Custom CSS
extra_css:
  - stylesheets/extra.css

extra:
  author:
    name: "Sudharsan Kesavanarayanan"
    title: "Azure AI Search Expert & Technical Author"
    bio: "Passionate about making Azure AI Search accessible to developers worldwide. This handbook represents years of hands-on experience and best practices in search technology."
    bio_short: "Azure AI Search Expert sharing practical knowledge and best practices."
    avatar: "assets/images/profile.jpg"
    # Profile display options (set to true/false to enable/disable)
    show_footer_profile: true      # Shows profile in footer of all pages
    show_header_banner: false      # Shows profile banner at top of pages
    show_sidebar_card: false       # Shows profile card in sidebar
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sudharsank
      name: GitHub Profile
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/your-linkedin-profile
      name: LinkedIn Profile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-twitter-handle
      name: Twitter Profile
  version:
    provider: mike
  generator: false